
package xx.mx.uv.consumo.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "inventarioPort", targetNamespace = "t4is.uv.mx/inventario")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InventarioPort {


    /**
     * 
     * @param generarFolioRequest
     * @return
     *     returns xx.mx.uv.consumo.wsdl.GenerarFolioResponse
     */
    @WebMethod(operationName = "GenerarFolio")
    @WebResult(name = "GenerarFolioResponse", targetNamespace = "t4is.uv.mx/inventario", partName = "GenerarFolioResponse")
    public GenerarFolioResponse generarFolio(
        @WebParam(name = "GenerarFolioRequest", targetNamespace = "t4is.uv.mx/inventario", partName = "GenerarFolioRequest")
        GenerarFolioRequest generarFolioRequest);

}
