
package vv.mx.uv.consumo.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "facturasPort", targetNamespace = "t4is.uv.mx/facturas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FacturasPort {


    /**
     * 
     * @param recuperarFacturaRequest
     * @return
     *     returns vv.mx.uv.consumo.wsdl.RecuperarFacturaResponse
     */
    @WebMethod
    @WebResult(name = "recuperarFacturaResponse", targetNamespace = "t4is.uv.mx/facturas", partName = "recuperarFacturaResponse")
    public RecuperarFacturaResponse recuperarFactura(
        @WebParam(name = "recuperarFacturaRequest", targetNamespace = "t4is.uv.mx/facturas", partName = "recuperarFacturaRequest")
        RecuperarFacturaRequest recuperarFacturaRequest);

    /**
     * 
     * @param generarFacturaRequest
     * @return
     *     returns vv.mx.uv.consumo.wsdl.GenerarFacturaResponse
     */
    @WebMethod
    @WebResult(name = "generarFacturaResponse", targetNamespace = "t4is.uv.mx/facturas", partName = "generarFacturaResponse")
    public GenerarFacturaResponse generarFactura(
        @WebParam(name = "generarFacturaRequest", targetNamespace = "t4is.uv.mx/facturas", partName = "generarFacturaRequest")
        GenerarFacturaRequest generarFacturaRequest);

}
